/*
 * Copyright (C) 2015 jordi
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package geneal;
import Exceptions.BYException;
import Exceptions.LEException;
import Exceptions.dateException;
import static geneal.formutils.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jordi
 */
public class NewFill extends javax.swing.JFrame {

    private String stitol = "";
    private db.unio unio;
    private formLlista list;
    /**
     * Creates new form NewFill
     * @param un
     */
    public NewFill(formLlista list_, db.unio un) {
        list = list_;
        unio = un;
        stitol = "Nou fill de la fitxa "+un.getFitxa();
        initComponents();
        
        iniciar();
    }

    final private javax.swing.ComboBoxModel cbsexe = getModelSexe();
    
    private formLloc naixement, defuncio;
    private formData dataNaixement, dataDefuncio;
    
    private void iniciar(){
        
        naixement = new formLloc(this.c_1municipi,  this.c_1parroquia, this.c_1llogaret);
        defuncio = new formLloc(this.c_1dmunicipi,  this.c_1dparroquia, this.c_1dllogaret);
        dataNaixement = new formData(this.c_1dia,  this.c_1mes,  this.t_1any);
        dataDefuncio = new formData(this.c_1ddia,  this.c_1dmes,  this.t_1dany);
        
        this.t_llinatge1.setText(unio.getConjuge1().getLlinatge1());
        this.t_llinatge2.setText(unio.getConjuge2().getLlinatge1());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        l_e_conjuge1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_nom = new javax.swing.JTextField();
        t_llinatge1 = new javax.swing.JTextField();
        t_llinatge2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_1municipi = new javax.swing.JComboBox();
        c_1parroquia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        c_1llogaret = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        c_1dia = new javax.swing.JComboBox();
        c_1mes = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_1any = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        c_1dmunicipi = new javax.swing.JComboBox();
        c_1dparroquia = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c_1dllogaret = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        c_1ddia = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        c_1dmes = new javax.swing.JComboBox();
        t_1dany = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        c_1sexe = new javax.swing.JComboBox();
        b_afegirfill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_1comentaris = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(stitol);

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_e_conjuge1.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        l_e_conjuge1.setText(stitol);
        jPanel6.add(l_e_conjuge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Nom");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, -1, -1));

        t_nom.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(t_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, -1));

        t_llinatge1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(t_llinatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 260, -1));

        t_llinatge2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(t_llinatge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 310, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Primer llinatge");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Segon llinatge");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Naixement:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("Municipi");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 165, -1, -1));

        c_1municipi.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1municipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1municipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1municipiActionPerformed(evt);
            }
        });
        c_1municipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_1municipiFocusLost(evt);
            }
        });
        jPanel6.add(c_1municipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 192, 150, -1));

        c_1parroquia.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1parroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1parroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1parroquiaActionPerformed(evt);
            }
        });
        jPanel6.add(c_1parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 165, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Parroquia");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 94, -1));

        c_1llogaret.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1llogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1llogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1llogaretActionPerformed(evt);
            }
        });
        jPanel6.add(c_1llogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 148, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Llogaret");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 94, -1));

        c_1dia.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(c_1dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 90, -1));

        c_1mes.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1mesActionPerformed(evt);
            }
        });
        jPanel6.add(c_1mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 100, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Dia");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 94, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setText("Mes");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 94, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setText("Any");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 94, -1));

        t_1any.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(t_1any, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 120, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel13.setText("Defunció");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 237, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel14.setText("Municipi");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 272, -1, -1));

        c_1dmunicipi.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1dmunicipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1dmunicipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dmunicipiActionPerformed(evt);
            }
        });
        c_1dmunicipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_1dmunicipiFocusLost(evt);
            }
        });
        jPanel6.add(c_1dmunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 299, 150, -1));

        c_1dparroquia.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1dparroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1dparroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dparroquiaActionPerformed(evt);
            }
        });
        jPanel6.add(c_1dparroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 170, -1));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel15.setText("Parroquia");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 94, -1));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel16.setText("Llogaret");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 94, -1));

        c_1dllogaret.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1dllogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1dllogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dllogaretActionPerformed(evt);
            }
        });
        jPanel6.add(c_1dllogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 148, -1));

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel17.setText("Dia");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 94, -1));

        c_1ddia.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(c_1ddia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 90, -1));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel18.setText("Mes");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 94, -1));

        c_1dmes.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1dmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dmesActionPerformed(evt);
            }
        });
        jPanel6.add(c_1dmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 100, -1));

        t_1dany.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel6.add(t_1dany, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 120, -1));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel19.setText("Any");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 94, -1));

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel21.setText("Sexe");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 344, -1, -1));

        c_1sexe.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        c_1sexe.setModel(cbsexe);
        c_1sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1sexeActionPerformed(evt);
            }
        });
        jPanel6.add(c_1sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 379, 130, -1));

        b_afegirfill.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        b_afegirfill.setText("Afegir fill");
        b_afegirfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_afegirfillActionPerformed(evt);
            }
        });
        jPanel6.add(b_afegirfill, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 424, 160, -1));

        t_1comentaris.setColumns(20);
        t_1comentaris.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        t_1comentaris.setRows(5);
        jScrollPane1.setViewportView(t_1comentaris);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 379, 670, 86));

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel22.setText("Comentaris");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 344, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -120, -1, 100));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -120, 550, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_1municipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1municipiActionPerformed
        this.naixement.selectedMunicipi();
    }//GEN-LAST:event_c_1municipiActionPerformed

    private void c_1municipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_1municipiFocusLost
        
    }//GEN-LAST:event_c_1municipiFocusLost

    private void c_1mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_1mesActionPerformed

    private void c_1dmunicipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_1dmunicipiFocusLost
        
    }//GEN-LAST:event_c_1dmunicipiFocusLost

    private void c_1dparroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dparroquiaActionPerformed
        this.defuncio.selectedParroquia();
    }//GEN-LAST:event_c_1dparroquiaActionPerformed

    private void c_1dmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_1dmesActionPerformed

    private void c_1sexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1sexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_1sexeActionPerformed

    private void b_afegirfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_afegirfillActionPerformed
        boolean commit = true;
        db.lloc lnaixement = new db.lloc(), ldefuncio = new db.lloc();
        db.date dnaixement = new db.date(), ddefuncio = new db.date();
        if (t_nom.getText().isEmpty()){
            Exceptions.GException e = new Exceptions.GException("El nom d'aquest fill és nul."
                    + " No es pot introduir. Corregeix-ho i torna-ho a provar.",
                    "Error al introduir fill.", Exceptions.GException.LOW);
            e.show();
            commit = false;
        }
        try {
            lnaixement = naixement.getLloc();
        } catch (LEException ex) {
            commit = false;
            ex.setContext("naixement");
            ex.show();
        } catch (SQLException ex) {
            commit = false;
            Logger.getLogger(NewFill.class.getName()).log(Level.SEVERE, null, ex);
        } 
        try{
            dnaixement = dataNaixement.getDate();
        } catch(BYException e){
            commit = false;
            e.setContext("naixement");
            e.show();
        } catch (dateException ex) {
            commit = false;
            ex.setContext("naixement");
            ex.show();
        }
        try {
            ldefuncio = defuncio.getLloc();
        } catch (LEException ex) {
            commit = false;
            ex.setContext("defunció");
            ex.show();
        } catch (SQLException ex) {
            commit = false;
            Logger.getLogger(NewFill.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            ddefuncio = dataDefuncio.getDate();
        } catch(BYException e){
            commit = false;
            e.setContext("defunció");
            e.show();
        } catch (dateException ex) {
            commit = false;
            ex.setContext("defunció");
            ex.show();
        }
        
        if (commit){
            if (this.c_1sexe.getSelectedIndex() == 0){
                int i = JOptionPane.showConfirmDialog(null, "La persona que vols "
                        + "introduir no té sexe. \n Vols introduir-la igualment?", 
                        "Sexe no especificat", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (i != JOptionPane.YES_OPTION){
                    return;
                }
            }
            db.persona p = new db.persona();
            p.setNom(this.t_nom.getText());
            p.setLlinatge1(this.t_llinatge1.getText());
            p.setLlinatge2(this.t_llinatge2.getText());
            p.setLlocDefuncio(ldefuncio.getId());
            p.setDataDefuncio(ddefuncio);
            p.setSexe(getSexe(this.c_1sexe));
            p.setComentaris(this.t_1comentaris.getText());
            int id_p = p.addPersona();
            db.naixement n = new db.naixement();
            n.setUnio(unio);
            n.setFill(id_p);
            n.setDate(dnaixement);
            n.setLloc(lnaixement.getId());
            n.addNaixement();
            
            list.add(p);
            this.dispose();
        }
                    
        
    }//GEN-LAST:event_b_afegirfillActionPerformed

    private void c_1dmunicipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dmunicipiActionPerformed
        this.defuncio.selectedMunicipi();
    }//GEN-LAST:event_c_1dmunicipiActionPerformed

    private void c_1parroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1parroquiaActionPerformed
        this.naixement.selectedParroquia();
    }//GEN-LAST:event_c_1parroquiaActionPerformed

    private void c_1llogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1llogaretActionPerformed
        this.naixement.selectedLlogaret();
    }//GEN-LAST:event_c_1llogaretActionPerformed

    private void c_1dllogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dllogaretActionPerformed
        this.defuncio.selectedLlogaret();
    }//GEN-LAST:event_c_1dllogaretActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_afegirfill;
    private javax.swing.JComboBox c_1ddia;
    private javax.swing.JComboBox c_1dia;
    private javax.swing.JComboBox c_1dllogaret;
    private javax.swing.JComboBox c_1dmes;
    private javax.swing.JComboBox c_1dmunicipi;
    private javax.swing.JComboBox c_1dparroquia;
    private javax.swing.JComboBox c_1llogaret;
    private javax.swing.JComboBox c_1mes;
    private javax.swing.JComboBox c_1municipi;
    private javax.swing.JComboBox c_1parroquia;
    private javax.swing.JComboBox c_1sexe;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel l_e_conjuge1;
    private javax.swing.JTextField t_1any;
    private javax.swing.JTextArea t_1comentaris;
    private javax.swing.JTextField t_1dany;
    private javax.swing.JTextField t_llinatge1;
    private javax.swing.JTextField t_llinatge2;
    private javax.swing.JTextField t_nom;
    // End of variables declaration//GEN-END:variables
}
