/*
 * Copyright (C) 2015 jordi
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package geneal;

import Exceptions.DBException;
import Exceptions.MUException;
import db.persona;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jordi
 */
public class taula extends javax.swing.JFrame {

    private DefaultTableModel model;
    private int fitxa;
    private formFitxa f;
    
    /**
     * Creates new form taula
     */
    public taula(formFitxa f_) {
        initComponents();
        
        f = f_;
        String[] municipis = db.municipi.getAll();
        geneal.formutils.fillCb(this.c_llocn, municipis);
        geneal.formutils.fillCb(this.c_llocd, municipis);
        
        int npersones = db.persona.count(), nunions = db.unio.count();
        this.l_total.setText("Total: "+npersones+" persones, "+nunions+" unions.");
        find();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        mi_carregar = new javax.swing.JMenuItem();
        scrollpane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t_nom = new javax.swing.JTextField();
        t_llin1 = new javax.swing.JTextField();
        t_llin2 = new javax.swing.JTextField();
        l_total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l_info = new javax.swing.JLabel();
        b_cerca = new javax.swing.JButton();
        c_llocd = new javax.swing.JComboBox();
        c_llocn = new javax.swing.JComboBox();

        mi_carregar.setText("Carregar");
        mi_carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_carregarActionPerformed(evt);
            }
        });
        popup.add(mi_carregar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(28);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollpane.setViewportView(table);

        getContentPane().add(scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1380, 650));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Lloc defunció");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, -1));

        t_nom.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        getContentPane().add(t_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        t_llin1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        getContentPane().add(t_llin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, -1));

        t_llin2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        getContentPane().add(t_llin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 200, -1));

        l_total.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        l_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_total.setText("jLabel1");
        getContentPane().add(l_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 780, 430, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Primer llinatge");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Segon llinatge");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Lloc naixement");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        l_info.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        l_info.setText("jLabel1");
        getContentPane().add(l_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 780, -1, -1));

        b_cerca.setText("Cerca");
        b_cerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cercaActionPerformed(evt);
            }
        });
        getContentPane().add(b_cerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 110, -1));

        c_llocd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_llocd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_llocdActionPerformed(evt);
            }
        });
        getContentPane().add(c_llocd, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 160, -1));

        c_llocn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(c_llocn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cercaActionPerformed
        find();
    }//GEN-LAST:event_b_cercaActionPerformed

    private void c_llocdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_llocdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_llocdActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if ( SwingUtilities.isRightMouseButton(evt)){
            fitxa = Integer.parseInt((String) model.getValueAt(table.rowAtPoint(evt.getPoint()), 0));
            popup.show(table, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void mi_carregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_carregarActionPerformed
        f.fillFitxa(fitxa);
        this.dispose();
    }//GEN-LAST:event_mi_carregarActionPerformed

    private static String nullify(String in){
        if (in==null || in.isEmpty()){
            return null;
        }else{
            return in;
        }
    }
    private static String nullify(javax.swing.JComboBox in){
        if (in.getSelectedIndex()==0){
            return null;
        }else{
            return String.valueOf(in.getSelectedItem());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cerca;
    private javax.swing.JComboBox c_llocd;
    private javax.swing.JComboBox c_llocn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l_info;
    private javax.swing.JLabel l_total;
    private javax.swing.JMenuItem mi_carregar;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTextField t_llin1;
    private javax.swing.JTextField t_llin2;
    private javax.swing.JTextField t_nom;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void Add(persona p) {
        String[] values = new String [9];
        db.unio u;
        db.naixement n;
        try {
            u = db.unio.fromConjuge(p.getId());
        } catch (MUException ex) {
            Logger.getLogger(taula.class.getName()).log(Level.SEVERE, null, ex);
            u = new db.unio();
        } catch (DBException ex) {
            u = new db.unio();
        }
        try {
            n = new db.naixement(p.getId());
        } catch (DBException ex) {
            n = new db.naixement();
        }
        if (u.getFitxa()!=-1){
            values[0] = String.valueOf(u.getFitxa());
        }
        values[1] = p.getNom();
        values[2] = p.getLlinatge1();
        values[3] = p.getLlinatge2();
        values[4] = n.getDate().toString();
        values[5] = n.getLloc().getMunicipi();
        values[6] = p.getDataDefuncio().toString();
        values[7] = p.getLlocDefuncio().getMunicipi();
        values[8] = p.getSexe();
        model.addRow(values);
    }

    private void find() {
        String[] columns = {"Fitxa", "Nom", "Primer Llin.", "Segon Llin.", 
            "Data Naix.", "Lloc Naix.", "Data Def.", "Lloc Def.", "Sexe"},
                dades = new String [columns.length];
        db.persona[] people;
        javax.swing.JTextField[] nom = {t_nom, t_llin1, t_llin2};
        
        model = new DefaultTableModel(null, columns);
        
        int idx = 0;
        for (javax.swing.JTextField t : nom){
            dades[idx] = nullify(t.getText());
            idx++;
        }
        dades[3] = nullify(c_llocn);
        dades[4] = nullify(c_llocd);
        people = db.persona.search(dades);
        for (db.persona p : people){
            Add(p);
        }
        table.setModel(model);
        l_info.setText("S'han trobat "+table.getRowCount()+" persones.");
    }
    
}
