/*
 * Copyright (C) 2015 jordi
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package geneal.nbforms;

import Exceptions.*;
import geneal.sourceforms.formData;
import geneal.sourceforms.formFitxa;
import geneal.sourceforms.formLlista;
import geneal.sourceforms.formLloc;
import geneal.sourceforms.formPersonaFitxa;
import geneal.sourceforms.formPersonaVisor;
import static geneal.config.*;
import javax.swing.UIManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.UnsupportedLookAndFeelException;
import static geneal.sourceforms.formutils.*;
import geneal.sourceforms.genealEventHandler;
import geneal.sourceforms.popupPersonaCerca;
import geneal.sourceforms.popupPersonaFill;
import geneal.tree.tree;
import javax.swing.SwingUtilities;
import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jordi
 */
public class App extends javax.swing.JFrame {

    //private db.unio un; // Padrins paterns 25
    private formFitxa f;
    private genealEventHandler eh;
    private formLlista cerca, fills;
    //private ArrayList<Integer> lfills = new ArrayList<>(), lcerca = new ArrayList<>();
    
    private final static String newPares = "Afegir pares";
    private final static String newUnio = "Crear fitxa";
    /**
     * Creates new Geneal window
     */
    public App() {
        System.out.println("Benvingut a l'aplicació geneològica Geneal!");
        initialize();
    }
    
    
    // Callbacks lists' item clicked
    private void fillClicat(int idx){
        db.persona p = fills.getSelectedPerson();
        eh.clickPerson(p);
    }
    private void cercaFillClicat(int idx){
        db.persona p = cerca.getSelectedPerson();
        eh.clickPerson(p);
    }
    
    private int getRow(javax.swing.JList list, Point point){
	return list.locationToIndex(point);
    }
    
    // ComboBox Models
    final private javax.swing.ComboBoxModel cbsexe = getModelSexe();
    final private javax.swing.ComboBoxModel cbsexe2 = getModelSexe();
    
    
    private formLloc fmatrimoni, fnmarit, fdmarit, fnmuller,  fdmuller;
    private formData fdmatrimoni, fdnmarit, fddmarit, fdnmuller, fddmuller;
    private formPersonaVisor visor1,  visor2;
    private formPersonaFitxa c1;
    private formPersonaFitxa c2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEditor = new javax.swing.JPanel();
        topleft = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        c_casament = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_ucomentaris = new javax.swing.JTextArea();
        jLabel51 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        c_umunicipi = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        c_uparroquia = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        c_ullogaret = new javax.swing.JComboBox();
        jLabel46 = new javax.swing.JLabel();
        c_udia = new javax.swing.JComboBox();
        c_umes = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        c_uany = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        ll_ufills = new javax.swing.JList();
        b_afegirfill = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        t_fitxa = new javax.swing.JTextField();
        l_generacio = new javax.swing.JLabel();
        b_eafegir = new javax.swing.JButton();
        b_eborrar = new javax.swing.JButton();
        topright = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        treepanel = new javax.swing.JPanel();
        l_pare = new javax.swing.JLabel();
        l_ppare = new javax.swing.JLabel();
        l_pppare = new javax.swing.JLabel();
        l_mppare = new javax.swing.JLabel();
        l_mpare = new javax.swing.JLabel();
        l_pmpare = new javax.swing.JLabel();
        l_mmpare = new javax.swing.JLabel();
        l_mare = new javax.swing.JLabel();
        l_pmare = new javax.swing.JLabel();
        l_ppmare = new javax.swing.JLabel();
        l_mpmare = new javax.swing.JLabel();
        l_mmare = new javax.swing.JLabel();
        l_pmmare = new javax.swing.JLabel();
        l_mmmare = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        find_nom = new javax.swing.JTextField();
        find_llinatge1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        find_llinatge2 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        b_cerca = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        find_list = new javax.swing.JList();
        bottolleft = new javax.swing.JPanel();
        l_e_conjuge1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_e_1nom = new javax.swing.JTextField();
        t_e_1llinatge1 = new javax.swing.JTextField();
        t_e_1llinatge2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_1municipi = new javax.swing.JComboBox();
        c_1parroquia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        c_1llogaret = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        c_1dia = new javax.swing.JComboBox();
        c_1mes = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_1any = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        c_1dmunicipi = new javax.swing.JComboBox();
        c_1dparroquia = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c_1dllogaret = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        c_1ddia = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        c_1dmes = new javax.swing.JComboBox();
        t_1dany = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        c_1sexe = new javax.swing.JComboBox();
        b_1pares = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_1comentaris = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        bottomright = new javax.swing.JPanel();
        l_e_conjuge2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_2nom = new javax.swing.JTextField();
        t_2llinatge1 = new javax.swing.JTextField();
        t_2llinatge2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        c_2nmunicipi = new javax.swing.JComboBox();
        c_2nparroquia = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        c_2nllogaret = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        c_2ndia = new javax.swing.JComboBox();
        c_2nmes = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        t_2nany = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        c_2dmunicipi = new javax.swing.JComboBox();
        c_2dparroquia = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        c_2dllogaret = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        c_2ddia = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        c_2dmes = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        t_2dany = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        c_2sexe = new javax.swing.JComboBox();
        b_2pares = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_2comentaris = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        arbrePane = new javax.swing.JPanel();
        panelVisor = new javax.swing.JPanel();
        v_fitxa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        v_conj1 = new javax.swing.JLabel();
        v_h_nom = new javax.swing.JLabel();
        v_h_naixement = new javax.swing.JLabel();
        v_h_defuncio = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        v_h_pares = new javax.swing.JLabel();
        v_h_pare = new javax.swing.JLabel();
        v_h_mare = new javax.swing.JLabel();
        vb_h_pares = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        v_h_pares1 = new javax.swing.JLabel();
        v_h_ppare = new javax.swing.JLabel();
        v_h_mpare = new javax.swing.JLabel();
        vb_h_ppares = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        v_h_pares2 = new javax.swing.JLabel();
        v_h_pmare = new javax.swing.JLabel();
        v_h_mmare = new javax.swing.JLabel();
        vb_h_mpares = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        v_conj2 = new javax.swing.JLabel();
        v_m_nom = new javax.swing.JLabel();
        v_m_naixement = new javax.swing.JLabel();
        v_m_defuncio = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        v_m_pares = new javax.swing.JLabel();
        v_m_pare = new javax.swing.JLabel();
        v_m_mare = new javax.swing.JLabel();
        vb_m_pares = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        v_h_pares4 = new javax.swing.JLabel();
        v_m_ppare = new javax.swing.JLabel();
        v_m_mpare = new javax.swing.JLabel();
        vb_m_ppares = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        v_h_pares5 = new javax.swing.JLabel();
        v_m_pmare = new javax.swing.JLabel();
        v_m_mmare = new javax.swing.JLabel();
        vb_m_mpares = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mu_csv = new javax.swing.JMenuItem();
        mu_taula = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geneal");

        jTabbedPane1.setFont(normalFont);

        panelEditor.setFont(normalFont);
        panelEditor.setMinimumSize(new java.awt.Dimension(700, 550));
        panelEditor.setPreferredSize(new java.awt.Dimension(780, 715));
        panelEditor.setLayout(new java.awt.GridLayout(2, 2));

        topleft.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        topleft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(normalFont);
        jLabel43.setText("Unió");
        topleft.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 20));

        c_casament.setFont(normalFont);
        c_casament.setText("Casament");
        c_casament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_casamentActionPerformed(evt);
            }
        });
        topleft.add(c_casament, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel44.setFont(normalFont);
        jLabel44.setText("Comentaris");
        topleft.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        t_ucomentaris.setColumns(20);
        t_ucomentaris.setFont(normalFont);
        t_ucomentaris.setRows(5);
        jScrollPane3.setViewportView(t_ucomentaris);

        topleft.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 320, 50));

        jLabel51.setFont(normalFont);
        jLabel51.setText("Fills");
        topleft.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel41.setFont(smallFont);
        jLabel41.setText("Municipi");
        topleft.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        c_umunicipi.setEditable(true);
        c_umunicipi.setFont(normalFont);
        c_umunicipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_umunicipiActionPerformed(evt);
            }
        });
        c_umunicipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_umunicipiFocusLost(evt);
            }
        });
        c_umunicipi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_umunicipiKeyPressed(evt);
            }
        });
        topleft.add(c_umunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jLabel42.setFont(smallFont);
        jLabel42.setText("Parroquia");
        topleft.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 94, -1));

        c_uparroquia.setFont(normalFont);
        c_uparroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_uparroquiaActionPerformed(evt);
            }
        });
        topleft.add(c_uparroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 80, -1));

        jLabel45.setFont(smallFont);
        jLabel45.setText("Llogaret");
        topleft.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 94, -1));

        c_ullogaret.setFont(normalFont);
        c_ullogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_ullogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ullogaretActionPerformed(evt);
            }
        });
        topleft.add(c_ullogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 90, -1));

        jLabel46.setFont(smallFont);
        jLabel46.setText("Dia");
        topleft.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, -1));

        c_udia.setFont(normalFont);
        topleft.add(c_udia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 80, -1));

        c_umes.setFont(normalFont);
        c_umes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_umesActionPerformed(evt);
            }
        });
        topleft.add(c_umes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 70, -1));

        jLabel47.setFont(smallFont);
        jLabel47.setText("Mes");
        topleft.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, -1));

        jLabel48.setFont(smallFont);
        jLabel48.setText("Any");
        topleft.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 30, -1));

        c_uany.setFont(normalFont);
        topleft.add(c_uany, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 40, -1));

        ll_ufills.setFont(smallFont);
        ll_ufills.setVisibleRowCount(10);
        ll_ufills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ll_ufillsMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(ll_ufills);

        topleft.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 460, 50));

        b_afegirfill.setFont(normalFont);
        b_afegirfill.setText("Afegir fill");
        b_afegirfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_afegirfillActionPerformed(evt);
            }
        });
        topleft.add(b_afegirfill, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 70, 20));

        jLabel49.setFont(boldFont);
        jLabel49.setText("Fitxa");
        topleft.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        t_fitxa.setFont(normalFont);
        topleft.add(t_fitxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 20));

        l_generacio.setFont(normalFont);
        l_generacio.setText("Generació");
        topleft.add(l_generacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        b_eafegir.setFont(normalFont);
        b_eafegir.setText("Afegir fitxa");
        b_eafegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eafegirActionPerformed(evt);
            }
        });
        topleft.add(b_eafegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 20));

        b_eborrar.setFont(normalFont);
        b_eborrar.setText("Esborrar");
        b_eborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eborrarActionPerformed(evt);
            }
        });
        topleft.add(b_eborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 70, 20));

        panelEditor.add(topleft);

        treepanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        treepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_pare.setFont(normalFont);
        l_pare.setText("jLabel1");
        treepanel.add(l_pare, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        l_ppare.setFont(smallFont);
        l_ppare.setText("jLabel3");
        treepanel.add(l_ppare, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        l_pppare.setFont(tinyFont);
        l_pppare.setText("jLabel3");
        treepanel.add(l_pppare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        l_mppare.setFont(tinyFont);
        l_mppare.setText("jLabel3");
        treepanel.add(l_mppare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        l_mpare.setFont(smallFont);
        l_mpare.setText("jLabel3");
        treepanel.add(l_mpare, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        l_pmpare.setFont(tinyFont);
        l_pmpare.setText("jLabel3");
        treepanel.add(l_pmpare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        l_mmpare.setFont(tinyFont);
        l_mmpare.setText("jLabel3");
        treepanel.add(l_mmpare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        l_mare.setFont(normalFont);
        l_mare.setText("jLabel1");
        treepanel.add(l_mare, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        l_pmare.setFont(smallFont);
        l_pmare.setText("jLabel3");
        treepanel.add(l_pmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        l_ppmare.setFont(tinyFont);
        l_ppmare.setText("jLabel3");
        treepanel.add(l_ppmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        l_mpmare.setFont(tinyFont);
        l_mpmare.setText("jLabel3");
        treepanel.add(l_mpmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        l_mmare.setFont(smallFont);
        l_mmare.setText("jLabel3");
        treepanel.add(l_mmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        l_pmmare.setFont(tinyFont);
        l_pmmare.setText("jLabel3");
        treepanel.add(l_pmmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        l_mmmare.setFont(tinyFont);
        l_mmmare.setText("jLabel3");
        treepanel.add(l_mmmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jScrollPane16.setViewportView(treepanel);

        searchpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchpanel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(normalFont);
        jLabel52.setText("Nom");
        searchpanel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        find_nom.setFont(normalFont);
        searchpanel.add(find_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, 20));

        find_llinatge1.setFont(normalFont);
        searchpanel.add(find_llinatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 20));

        jLabel53.setFont(normalFont);
        jLabel53.setText("Llinatge 1");
        searchpanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        find_llinatge2.setFont(normalFont);
        searchpanel.add(find_llinatge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, 20));

        jLabel54.setFont(normalFont);
        jLabel54.setText("Llinatge 2");
        searchpanel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        b_cerca.setFont(normalFont);
        b_cerca.setText("Cercar");
        b_cerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cercaActionPerformed(evt);
            }
        });
        searchpanel.add(b_cerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, 20));

        jScrollPane8.setMaximumSize(new java.awt.Dimension(440, 175));

        find_list.setFont(smallFont);
        find_list.setMaximumSize(new java.awt.Dimension(435, 173));
        find_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                find_listMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(find_list);

        searchpanel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, 210));

        javax.swing.GroupLayout toprightLayout = new javax.swing.GroupLayout(topright);
        topright.setLayout(toprightLayout);
        toprightLayout.setHorizontalGroup(
            toprightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toprightLayout.createSequentialGroup()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3530, 3530, 3530))
        );
        toprightLayout.setVerticalGroup(
            toprightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(searchpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelEditor.add(topright);

        bottolleft.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bottolleft.setPreferredSize(new java.awt.Dimension(500, 320));
        bottolleft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_e_conjuge1.setFont(boldFont);
        l_e_conjuge1.setText("Conjuge1");
        bottolleft.add(l_e_conjuge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(normalFont);
        jLabel2.setText("Nom");
        bottolleft.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        t_e_1nom.setFont(normalFont);
        bottolleft.add(t_e_1nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, -1));

        t_e_1llinatge1.setFont(normalFont);
        bottolleft.add(t_e_1llinatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        t_e_1llinatge2.setFont(normalFont);
        bottolleft.add(t_e_1llinatge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 150, -1));

        jLabel4.setFont(normalFont);
        jLabel4.setText("Primer llinatge");
        bottolleft.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel5.setFont(normalFont);
        jLabel5.setText("Segon llinatge");
        bottolleft.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel6.setFont(normalFont);
        jLabel6.setText("Naixement:");
        bottolleft.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(smallFont);
        jLabel7.setText("Municipi");
        bottolleft.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        c_1municipi.setFont(normalFont);
        c_1municipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1municipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1municipiActionPerformed(evt);
            }
        });
        c_1municipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_1municipiFocusLost(evt);
            }
        });
        bottolleft.add(c_1municipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, -1));

        c_1parroquia.setFont(normalFont);
        c_1parroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1parroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1parroquiaActionPerformed(evt);
            }
        });
        bottolleft.add(c_1parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, -1));

        jLabel8.setFont(smallFont);
        jLabel8.setText("Parroquia");
        bottolleft.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 94, -1));

        c_1llogaret.setFont(normalFont);
        c_1llogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1llogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1llogaretActionPerformed(evt);
            }
        });
        bottolleft.add(c_1llogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, -1));

        jLabel9.setFont(smallFont);
        jLabel9.setText("Llogaret");
        bottolleft.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 94, -1));

        c_1dia.setFont(normalFont);
        bottolleft.add(c_1dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, -1));

        c_1mes.setFont(normalFont);
        c_1mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1mesActionPerformed(evt);
            }
        });
        bottolleft.add(c_1mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 60, -1));

        jLabel10.setFont(smallFont);
        jLabel10.setText("Dia");
        bottolleft.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 94, -1));

        jLabel11.setFont(smallFont);
        jLabel11.setText("Mes");
        bottolleft.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 94, -1));

        jLabel12.setFont(smallFont);
        jLabel12.setText("Any");
        bottolleft.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 70, -1));

        t_1any.setFont(normalFont);
        bottolleft.add(t_1any, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 50, -1));

        jLabel13.setFont(normalFont);
        jLabel13.setText("Defunció");
        bottolleft.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel14.setFont(smallFont);
        jLabel14.setText("Municipi");
        bottolleft.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        c_1dmunicipi.setFont(normalFont);
        c_1dmunicipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1dmunicipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dmunicipiActionPerformed(evt);
            }
        });
        c_1dmunicipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_1dmunicipiFocusLost(evt);
            }
        });
        bottolleft.add(c_1dmunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        c_1dparroquia.setFont(normalFont);
        c_1dparroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1dparroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dparroquiaActionPerformed(evt);
            }
        });
        bottolleft.add(c_1dparroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 90, -1));

        jLabel15.setFont(smallFont);
        jLabel15.setText("Parroquia");
        bottolleft.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 94, -1));

        jLabel16.setFont(smallFont);
        jLabel16.setText("Llogaret");
        bottolleft.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 94, -1));

        c_1dllogaret.setFont(normalFont);
        c_1dllogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_1dllogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dllogaretActionPerformed(evt);
            }
        });
        bottolleft.add(c_1dllogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, -1));

        jLabel17.setFont(smallFont);
        jLabel17.setText("Dia");
        bottolleft.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 94, -1));

        c_1ddia.setFont(normalFont);
        bottolleft.add(c_1ddia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, -1));

        jLabel18.setFont(smallFont);
        jLabel18.setText("Mes");
        bottolleft.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 94, -1));

        c_1dmes.setFont(normalFont);
        c_1dmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1dmesActionPerformed(evt);
            }
        });
        bottolleft.add(c_1dmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 60, -1));

        t_1dany.setFont(normalFont);
        t_1dany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_1danyActionPerformed(evt);
            }
        });
        bottolleft.add(t_1dany, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 50, -1));

        jLabel19.setFont(smallFont);
        jLabel19.setText("Any");
        bottolleft.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 50, -1));

        jLabel21.setFont(normalFont);
        jLabel21.setText("Sexe");
        bottolleft.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        c_1sexe.setFont(normalFont);
        c_1sexe.setModel(cbsexe);
        c_1sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_1sexeActionPerformed(evt);
            }
        });
        bottolleft.add(c_1sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 20));

        b_1pares.setFont(normalFont);
        b_1pares.setText("Fitxa pares");
        b_1pares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1paresActionPerformed(evt);
            }
        });
        bottolleft.add(b_1pares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 20));

        t_1comentaris.setColumns(20);
        t_1comentaris.setFont(normalFont);
        t_1comentaris.setRows(5);
        jScrollPane1.setViewportView(t_1comentaris);

        bottolleft.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 340, 40));

        jLabel22.setFont(normalFont);
        jLabel22.setText("Comentaris");
        bottolleft.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        bottolleft.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -120, -1, 100));

        panelEditor.add(bottolleft);

        bottomright.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bottomright.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_e_conjuge2.setFont(boldFont);
        l_e_conjuge2.setText("Conjuge1");
        bottomright.add(l_e_conjuge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jLabel20.setFont(normalFont);
        jLabel20.setText("Nom");
        bottomright.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        t_2nom.setFont(normalFont);
        bottomright.add(t_2nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, -1));

        t_2llinatge1.setFont(normalFont);
        bottomright.add(t_2llinatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, -1));

        t_2llinatge2.setFont(normalFont);
        bottomright.add(t_2llinatge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, -1));

        jLabel23.setFont(normalFont);
        jLabel23.setText("Primer llinatge");
        bottomright.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel24.setFont(normalFont);
        jLabel24.setText("Segon llinatge");
        bottomright.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, -1));

        jLabel25.setFont(normalFont);
        jLabel25.setText("Naixement:");
        bottomright.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel26.setFont(smallFont);
        jLabel26.setText("Municipi");
        bottomright.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        c_2nmunicipi.setFont(normalFont);
        c_2nmunicipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_2nmunicipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2nmunicipiActionPerformed(evt);
            }
        });
        c_2nmunicipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_2nmunicipiFocusLost(evt);
            }
        });
        bottomright.add(c_2nmunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        c_2nparroquia.setFont(normalFont);
        c_2nparroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_2nparroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2nparroquiaActionPerformed(evt);
            }
        });
        bottomright.add(c_2nparroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, -1));

        jLabel27.setFont(smallFont);
        jLabel27.setText("Parroquia");
        bottomright.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 94, -1));

        c_2nllogaret.setFont(normalFont);
        c_2nllogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_2nllogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2nllogaretActionPerformed(evt);
            }
        });
        bottomright.add(c_2nllogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 90, -1));

        jLabel28.setFont(smallFont);
        jLabel28.setText("Llogaret");
        bottomright.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 94, -1));

        c_2ndia.setFont(normalFont);
        bottomright.add(c_2ndia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 70, -1));

        c_2nmes.setFont(normalFont);
        c_2nmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2nmesActionPerformed(evt);
            }
        });
        bottomright.add(c_2nmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 60, -1));

        jLabel29.setFont(smallFont);
        jLabel29.setText("Dia");
        bottomright.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, -1));

        jLabel30.setFont(smallFont);
        jLabel30.setText("Mes");
        bottomright.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 60, -1));

        jLabel31.setFont(smallFont);
        jLabel31.setText("Any");
        bottomright.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 30, -1));

        t_2nany.setFont(normalFont);
        bottomright.add(t_2nany, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 40, -1));

        jLabel32.setFont(normalFont);
        jLabel32.setText("Defunció");
        bottomright.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel33.setFont(smallFont);
        jLabel33.setText("Municipi");
        bottomright.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        c_2dmunicipi.setFont(normalFont);
        c_2dmunicipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_2dmunicipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2dmunicipiActionPerformed(evt);
            }
        });
        c_2dmunicipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_2dmunicipiFocusLost(evt);
            }
        });
        bottomright.add(c_2dmunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));

        c_2dparroquia.setFont(normalFont);
        c_2dparroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_2dparroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2dparroquiaActionPerformed(evt);
            }
        });
        bottomright.add(c_2dparroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 80, -1));

        jLabel34.setFont(smallFont);
        jLabel34.setText("Parroquia");
        bottomright.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 94, -1));

        jLabel35.setFont(smallFont);
        jLabel35.setText("Llogaret");
        bottomright.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 94, -1));

        c_2dllogaret.setFont(normalFont);
        c_2dllogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_2dllogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2dllogaretActionPerformed(evt);
            }
        });
        bottomright.add(c_2dllogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 90, -1));

        jLabel36.setFont(smallFont);
        jLabel36.setText("Dia");
        bottomright.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 94, -1));

        c_2ddia.setFont(normalFont);
        bottomright.add(c_2ddia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 70, -1));

        jLabel37.setFont(smallFont);
        jLabel37.setText("Mes");
        bottomright.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 60, -1));

        c_2dmes.setFont(normalFont);
        c_2dmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2dmesActionPerformed(evt);
            }
        });
        bottomright.add(c_2dmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 60, -1));

        jLabel38.setFont(smallFont);
        jLabel38.setText("Any");
        bottomright.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 30, -1));

        t_2dany.setFont(normalFont);
        bottomright.add(t_2dany, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, -1));

        jLabel39.setFont(normalFont);
        jLabel39.setText("Sexe");
        bottomright.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        c_2sexe.setFont(normalFont);
        c_2sexe.setModel(cbsexe2);
        c_2sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_2sexeActionPerformed(evt);
            }
        });
        bottomright.add(c_2sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 20));

        b_2pares.setFont(normalFont);
        b_2pares.setText("Fitxa pares");
        b_2pares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2paresActionPerformed(evt);
            }
        });
        bottomright.add(b_2pares, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, 20));

        t_2comentaris.setColumns(20);
        t_2comentaris.setFont(normalFont);
        t_2comentaris.setRows(5);
        jScrollPane2.setViewportView(t_2comentaris);

        bottomright.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 310, 40));

        jLabel40.setFont(normalFont);
        jLabel40.setText("Comentaris");
        bottomright.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        panelEditor.add(bottomright);

        jTabbedPane1.addTab("Editor", panelEditor);

        javax.swing.GroupLayout arbrePaneLayout = new javax.swing.GroupLayout(arbrePane);
        arbrePane.setLayout(arbrePaneLayout);
        arbrePaneLayout.setHorizontalGroup(
            arbrePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        arbrePaneLayout.setVerticalGroup(
            arbrePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Arbre", arbrePane);

        panelVisor.setFont(normalFont);

        v_fitxa.setText("Fitxa: ");

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_conj1.setFont(bigBoldFont);
        v_conj1.setText("Home");
        jPanel1.add(v_conj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_h_nom.setFont(bigFont);
        v_h_nom.setText("nom");
        jPanel1.add(v_h_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_h_naixement.setFont(bigFont);
        v_h_naixement.setText("naixement");
        jPanel1.add(v_h_naixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        v_h_defuncio.setFont(bigFont);
        v_h_defuncio.setText("defunció");
        jPanel1.add(v_h_defuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jPanel3.add(jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_h_pares.setFont(bigBoldFont);
        v_h_pares.setText("Pares");
        jPanel5.add(v_h_pares, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_h_pare.setFont(bigFont);
        v_h_pare.setText("nomPare");
        jPanel5.add(v_h_pare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_h_mare.setFont(bigFont);
        v_h_mare.setText("nomMare");
        jPanel5.add(v_h_mare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        vb_h_pares.setFont(bigFont);
        vb_h_pares.setText("jButton1");
        vb_h_pares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vb_h_paresActionPerformed(evt);
            }
        });
        jPanel5.add(vb_h_pares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel3.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_h_pares1.setFont(bigBoldFont);
        v_h_pares1.setText("Padrins paterns");
        jPanel6.add(v_h_pares1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_h_ppare.setFont(bigFont);
        v_h_ppare.setText("nomPare");
        jPanel6.add(v_h_ppare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_h_mpare.setFont(bigFont);
        v_h_mpare.setText("nomMare");
        jPanel6.add(v_h_mpare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        vb_h_ppares.setFont(bigFont);
        vb_h_ppares.setText("jButton1");
        vb_h_ppares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vb_h_pparesActionPerformed(evt);
            }
        });
        jPanel6.add(vb_h_ppares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel3.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_h_pares2.setFont(bigBoldFont);
        v_h_pares2.setText("Padrins materns");
        jPanel7.add(v_h_pares2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_h_pmare.setFont(bigFont);
        v_h_pmare.setText("nomPare");
        jPanel7.add(v_h_pmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_h_mmare.setFont(bigFont);
        v_h_mmare.setText("nomMare");
        jPanel7.add(v_h_mmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        vb_h_mpares.setFont(bigFont);
        vb_h_mpares.setText("jButton1");
        vb_h_mpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vb_h_mparesActionPerformed(evt);
            }
        });
        jPanel7.add(vb_h_mpares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel3.add(jPanel7);

        jPanel2.add(jPanel3);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new java.awt.GridLayout(4, 1));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_conj2.setFont(bigBoldFont);
        v_conj2.setText("Dona");
        jPanel10.add(v_conj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_m_nom.setFont(bigFont);
        v_m_nom.setText("nom");
        jPanel10.add(v_m_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_m_naixement.setFont(bigFont);
        v_m_naixement.setText("naixement");
        jPanel10.add(v_m_naixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        v_m_defuncio.setFont(bigFont);
        v_m_defuncio.setText("defunció");
        jPanel10.add(v_m_defuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jPanel9.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_m_pares.setFont(bigBoldFont);
        v_m_pares.setText("Pares");
        jPanel11.add(v_m_pares, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_m_pare.setFont(bigFont);
        v_m_pare.setText("nomPare");
        jPanel11.add(v_m_pare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_m_mare.setFont(bigFont);
        v_m_mare.setText("nomMare");
        jPanel11.add(v_m_mare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        vb_m_pares.setFont(bigFont);
        vb_m_pares.setText("jButton1");
        vb_m_pares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vb_m_paresActionPerformed(evt);
            }
        });
        jPanel11.add(vb_m_pares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel9.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_h_pares4.setFont(bigBoldFont);
        v_h_pares4.setText("Padrins paterns");
        jPanel12.add(v_h_pares4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_m_ppare.setFont(bigFont);
        v_m_ppare.setText("nomPare");
        jPanel12.add(v_m_ppare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_m_mpare.setFont(bigFont);
        v_m_mpare.setText("nomMare");
        jPanel12.add(v_m_mpare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        vb_m_ppares.setFont(bigFont);
        vb_m_ppares.setText("jButton1");
        vb_m_ppares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vb_m_pparesActionPerformed(evt);
            }
        });
        jPanel12.add(vb_m_ppares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel9.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v_h_pares5.setFont(bigBoldFont);
        v_h_pares5.setText("Padrins materns");
        jPanel13.add(v_h_pares5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        v_m_pmare.setFont(bigFont);
        v_m_pmare.setText("nomPare");
        jPanel13.add(v_m_pmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        v_m_mmare.setFont(bigFont);
        v_m_mmare.setText("nomMare");
        jPanel13.add(v_m_mmare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        vb_m_mpares.setFont(bigFont);
        vb_m_mpares.setText("jButton1");
        vb_m_mpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vb_m_mparesActionPerformed(evt);
            }
        });
        jPanel13.add(vb_m_mpares, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jPanel9.add(jPanel13);

        jPanel8.add(jPanel9);

        jPanel2.add(jPanel8);

        javax.swing.GroupLayout panelVisorLayout = new javax.swing.GroupLayout(panelVisor);
        panelVisor.setLayout(panelVisorLayout);
        panelVisorLayout.setHorizontalGroup(
            panelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_fitxa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelVisorLayout.setVerticalGroup(
            panelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_fitxa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visor", panelVisor);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Fitxa");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Obrir fitxa");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Surt");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Eines");

        mu_csv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mu_csv.setMnemonic('t');
        mu_csv.setText("Generar llistes");
        mu_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mu_csvActionPerformed(evt);
            }
        });
        editMenu.add(mu_csv);

        mu_taula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mu_taula.setMnemonic('t');
        mu_taula.setText("Taula");
        mu_taula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mu_taulaActionPerformed(evt);
            }
        });
        editMenu.add(mu_taula);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ajuda");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sobre Geneal");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Editor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        tancar();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        novaFitxa();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void mu_taulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mu_taulaActionPerformed
        new taula(f).setVisible(true);
    }//GEN-LAST:event_mu_taulaActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new GException("Aquesta opció encara no la he programat. \n\t:(","Opció no suportada").show();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void mu_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mu_csvActionPerformed
        new CSVgenerate.formCSV().setVisible(true);
    }//GEN-LAST:event_mu_csvActionPerformed

    private void b_1paresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1paresActionPerformed
        eh.loadPares(formFitxa.home);
    }//GEN-LAST:event_b_1paresActionPerformed

    private void c_1sexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1sexeActionPerformed
        this.l_e_conjuge1.setText(String.valueOf(this.c_1sexe.getSelectedItem()));
    }//GEN-LAST:event_c_1sexeActionPerformed

    private void c_1dmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_1dmesActionPerformed

    private void c_1dllogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dllogaretActionPerformed
        this.fdmarit.selectedLlogaret();
    }//GEN-LAST:event_c_1dllogaretActionPerformed

    private void c_1dparroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dparroquiaActionPerformed
        this.fdmarit.selectedParroquia();
    }//GEN-LAST:event_c_1dparroquiaActionPerformed

    private void c_1dmunicipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_1dmunicipiFocusLost
        this.fdmarit.selectedMunicipi();
    }//GEN-LAST:event_c_1dmunicipiFocusLost

    private void c_1dmunicipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1dmunicipiActionPerformed
        this.fdmarit.selectedMunicipi();
    }//GEN-LAST:event_c_1dmunicipiActionPerformed

    private void c_1mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_1mesActionPerformed

    private void c_1llogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1llogaretActionPerformed
        this.fnmarit.selectedLlogaret();
    }//GEN-LAST:event_c_1llogaretActionPerformed

    private void c_1parroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1parroquiaActionPerformed
        this.fnmarit.selectedParroquia();
    }//GEN-LAST:event_c_1parroquiaActionPerformed

    private void c_1municipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_1municipiFocusLost
        this.fnmarit.selectedMunicipi();
    }//GEN-LAST:event_c_1municipiFocusLost

    private void c_1municipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_1municipiActionPerformed
        this.fnmarit.selectedMunicipi();
    }//GEN-LAST:event_c_1municipiActionPerformed

    private void b_2paresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2paresActionPerformed
        eh.loadPares(formFitxa.dona);
    }//GEN-LAST:event_b_2paresActionPerformed

    private void c_2sexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2sexeActionPerformed
        this.l_e_conjuge2.setText(String.valueOf(this.c_2sexe.getSelectedItem()));
    }//GEN-LAST:event_c_2sexeActionPerformed

    private void c_2dmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2dmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_2dmesActionPerformed

    private void c_2dllogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2dllogaretActionPerformed
        this.fdmuller.selectedLlogaret();
    }//GEN-LAST:event_c_2dllogaretActionPerformed

    private void c_2dparroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2dparroquiaActionPerformed
        this.fdmuller.selectedParroquia();
    }//GEN-LAST:event_c_2dparroquiaActionPerformed

    private void c_2dmunicipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_2dmunicipiFocusLost
        this.fdmuller.selectedMunicipi();
    }//GEN-LAST:event_c_2dmunicipiFocusLost

    private void c_2dmunicipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2dmunicipiActionPerformed
        this.fdmuller.selectedMunicipi();
    }//GEN-LAST:event_c_2dmunicipiActionPerformed

    private void c_2nmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2nmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_2nmesActionPerformed

    private void c_2nllogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2nllogaretActionPerformed
        this.fnmuller.selectedLlogaret();
    }//GEN-LAST:event_c_2nllogaretActionPerformed

    private void c_2nparroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2nparroquiaActionPerformed
        this.fnmuller.selectedParroquia();
    }//GEN-LAST:event_c_2nparroquiaActionPerformed

    private void c_2nmunicipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_2nmunicipiFocusLost
        this.fnmuller.selectedMunicipi();
    }//GEN-LAST:event_c_2nmunicipiFocusLost

    private void c_2nmunicipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_2nmunicipiActionPerformed
        this.fnmuller.selectedMunicipi();
    }//GEN-LAST:event_c_2nmunicipiActionPerformed

    private void find_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_find_listMouseClicked
        if ( SwingUtilities.isRightMouseButton(evt)){
            this.find_list.setSelectedIndex(getRow(this.find_list, evt.getPoint()));
            db.persona p = cerca.getSelectedPerson();
            ppc.show(find_list, evt.getX(), evt.getY(), p);
        }
    }//GEN-LAST:event_find_listMouseClicked

    private void b_cercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cercaActionPerformed
        db.persona[] ps = db.persona.getPeopleLike(find_nom.getText(),
            find_llinatge1.getText(), find_llinatge2.getText());
        cerca.fillList(ps);
    }//GEN-LAST:event_b_cercaActionPerformed

    private void b_eafegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eafegirActionPerformed
        f.committ();
    }//GEN-LAST:event_b_eafegirActionPerformed

    private void b_afegirfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_afegirfillActionPerformed
        new NewFill(fills,f.getUnio()).setVisible(true);
    }//GEN-LAST:event_b_afegirfillActionPerformed

    private void ll_ufillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ll_ufillsMouseClicked
        if ( SwingUtilities.isRightMouseButton(evt)){
            this.ll_ufills.setSelectedIndex(getRow(this.ll_ufills, evt.getPoint()));
            db.persona p = fills.getSelectedPerson();
            ppf.show(ll_ufills, evt.getX(), evt.getY(), p);
        }
    }//GEN-LAST:event_ll_ufillsMouseClicked

    private void c_umesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_umesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_umesActionPerformed

    private void c_ullogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ullogaretActionPerformed
        this.fmatrimoni.selectedLlogaret();
    }//GEN-LAST:event_c_ullogaretActionPerformed

    private void c_uparroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_uparroquiaActionPerformed
        this.fmatrimoni.selectedParroquia();
    }//GEN-LAST:event_c_uparroquiaActionPerformed

    private void c_umunicipiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_umunicipiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_umunicipiKeyPressed

    private void c_umunicipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_umunicipiFocusLost
        this.fmatrimoni.selectedMunicipi();
    }//GEN-LAST:event_c_umunicipiFocusLost

    private void c_umunicipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_umunicipiActionPerformed
        this.fmatrimoni.selectedMunicipi();
    }//GEN-LAST:event_c_umunicipiActionPerformed

    private void c_casamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_casamentActionPerformed
        f.ActionPerformedCasament();
    }//GEN-LAST:event_c_casamentActionPerformed

    private void t_1danyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_1danyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_1danyActionPerformed

    private void vb_h_paresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vb_h_paresActionPerformed
        f.fillFitxa(this.visor1.getFitxa(formPersonaVisor.pares));
    }//GEN-LAST:event_vb_h_paresActionPerformed

    private void vb_h_pparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vb_h_pparesActionPerformed
        f.fillFitxa(this.visor1.getFitxa(formPersonaVisor.padrinsPaterns));
    }//GEN-LAST:event_vb_h_pparesActionPerformed

    private void vb_h_mparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vb_h_mparesActionPerformed
        f.fillFitxa(this.visor1.getFitxa(formPersonaVisor.padrinsMaterns));
    }//GEN-LAST:event_vb_h_mparesActionPerformed

    private void vb_m_paresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vb_m_paresActionPerformed
        f.fillFitxa(this.visor2.getFitxa(formPersonaVisor.pares));
    }//GEN-LAST:event_vb_m_paresActionPerformed

    private void vb_m_pparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vb_m_pparesActionPerformed
        f.fillFitxa(this.visor2.getFitxa(formPersonaVisor.padrinsPaterns));
    }//GEN-LAST:event_vb_m_pparesActionPerformed

    private void vb_m_mparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vb_m_mparesActionPerformed
        f.fillFitxa(this.visor2.getFitxa(formPersonaVisor.padrinsMaterns));
    }//GEN-LAST:event_vb_m_mparesActionPerformed

    private void b_eborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eborrarActionPerformed
        f.delete();
    }//GEN-LAST:event_b_eborrarActionPerformed
    
    
    private void initialize(){
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel"); 
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                UnsupportedLookAndFeelException ex) {}
        initComponents();
        tree t = new tree(arbrePane);
        arbrePane.add(t);
             
        this.setVisible(true);
        
        db.unio un = new db.unio();
        
        ll_ufills.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                javax.swing.JList list = (javax.swing.JList)evt.getSource();
                if (evt.getClickCount() == 2) {

                    // Double-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    fillClicat(index);
                } 
            }
        });
        
        this.find_list.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                javax.swing.JList list = (javax.swing.JList)evt.getSource();
                if (evt.getClickCount() == 2) {

                    // Double-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    cercaFillClicat(index);
                }
            }
        });
        

        fmatrimoni = new formLloc(this.c_umunicipi, this.c_uparroquia,  this.c_ullogaret);
        fnmarit = new formLloc(this.c_1municipi, this.c_1parroquia,  this.c_1llogaret);
        fdmarit = new formLloc(this.c_1dmunicipi, this.c_1dparroquia,  this.c_1dllogaret);
        fnmuller = new formLloc(this.c_2nmunicipi, this.c_2nparroquia,  this.c_2nllogaret);
        fdmuller = new formLloc(this.c_2dmunicipi, this.c_2dparroquia,  this.c_2dllogaret);

        fdmatrimoni = new formData(this.c_udia, this.c_umes, this.c_uany);
        fdnmarit = new formData(this.c_1dia, this.c_1mes, this.t_1any);
        fddmarit = new formData(this.c_1ddia, this.c_1dmes, this.t_1dany);
        fdnmuller = new formData(this.c_2ndia, this.c_2nmes, this.t_2nany);
        fddmuller = new formData(this.c_2ddia, this.c_2dmes, this.t_2dany);
        
        javax.swing.JTextField[] nomC1 = {this.t_e_1nom, this.t_e_1llinatge1,
                this.t_e_1llinatge2};
        javax.swing.JTextField[] nomC2 = {this.t_2nom, this.t_2llinatge1,
                this.t_2llinatge2};
        
        javax.swing.JLabel[] tree1 = {this.l_pare, this.l_ppare,  this.l_pppare,
                this.l_mppare, this.l_mpare, this.l_pmpare, this.l_mmpare};
        javax.swing.JLabel[] tree2 = {this.l_mare, this.l_pmare,  this.l_ppmare,
                this.l_mpmare, this.l_mmare, this.l_pmmare, this.l_mmmare};
        
        javax.swing.JLabel[] l_visor1 = {this.v_h_nom, this.v_h_pare, this.v_h_ppare,
            this.v_h_mpare, this.v_h_mare, this.v_h_pmare,  this.v_h_mmare};
        javax.swing.JLabel[] l_visor2 = {this.v_m_nom, this.v_m_pare, this.v_m_ppare,
            this.v_m_mpare, this.v_m_mare, this.v_m_pmare,  this.v_m_mmare};
        
        javax.swing.JButton[] b_visor1={this.vb_h_pares, this.vb_h_ppares,  this.vb_h_mpares};
        javax.swing.JButton[] b_visor2={this.vb_m_pares, this.vb_m_ppares,  this.vb_m_mpares};
        
        visor1=new formPersonaVisor(l_visor1, b_visor1, this.v_h_naixement, this.v_h_defuncio);
        visor2=new formPersonaVisor(l_visor2, b_visor2, this.v_m_naixement, this.v_m_defuncio);
        
        c1 = new formPersonaFitxa(un.getConjuge1().getId(), fnmarit, 
                fdmarit, fdnmarit, fddmarit, nomC1, t_1comentaris, c_1sexe,
                l_e_conjuge1, tree1, geneal.sourceforms.formPersona.Conjuge1, b_1pares, visor1);
        c2 = new formPersonaFitxa(un.getConjuge2().getId(), fnmuller, 
                fdmuller, fdnmuller, fddmuller, nomC2, t_2comentaris, c_2sexe,
                l_e_conjuge2, tree2, geneal.sourceforms.formPersona.Conjuge2, b_2pares, visor2);
        
        fills = new formLlista(this.ll_ufills);
        cerca = new formLlista(this.find_list);
        
        f = new formFitxa(un, c1, c2, t_fitxa,  t_ucomentaris, c_casament, fills,
                fmatrimoni, fdmatrimoni, v_fitxa,  t);
        
        eh = new genealEventHandler(f, this.jTabbedPane1);
        
        ppc = new popupPersonaCerca(cerca);
        ppf = new popupPersonaFill();
        
        novaFitxa();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        new App().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel arbrePane;
    private javax.swing.JButton b_1pares;
    private javax.swing.JButton b_2pares;
    private javax.swing.JButton b_afegirfill;
    private javax.swing.JButton b_cerca;
    private javax.swing.JButton b_eafegir;
    private javax.swing.JButton b_eborrar;
    private javax.swing.JPanel bottolleft;
    private javax.swing.JPanel bottomright;
    private javax.swing.JComboBox c_1ddia;
    private javax.swing.JComboBox c_1dia;
    private javax.swing.JComboBox c_1dllogaret;
    private javax.swing.JComboBox c_1dmes;
    private javax.swing.JComboBox c_1dmunicipi;
    private javax.swing.JComboBox c_1dparroquia;
    private javax.swing.JComboBox c_1llogaret;
    private javax.swing.JComboBox c_1mes;
    private javax.swing.JComboBox c_1municipi;
    private javax.swing.JComboBox c_1parroquia;
    private javax.swing.JComboBox c_1sexe;
    private javax.swing.JComboBox c_2ddia;
    private javax.swing.JComboBox c_2dllogaret;
    private javax.swing.JComboBox c_2dmes;
    private javax.swing.JComboBox c_2dmunicipi;
    private javax.swing.JComboBox c_2dparroquia;
    private javax.swing.JComboBox c_2ndia;
    private javax.swing.JComboBox c_2nllogaret;
    private javax.swing.JComboBox c_2nmes;
    private javax.swing.JComboBox c_2nmunicipi;
    private javax.swing.JComboBox c_2nparroquia;
    private javax.swing.JComboBox c_2sexe;
    private javax.swing.JCheckBox c_casament;
    private javax.swing.JTextField c_uany;
    private javax.swing.JComboBox c_udia;
    private javax.swing.JComboBox c_ullogaret;
    private javax.swing.JComboBox c_umes;
    private javax.swing.JComboBox c_umunicipi;
    private javax.swing.JComboBox c_uparroquia;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JList find_list;
    private javax.swing.JTextField find_llinatge1;
    private javax.swing.JTextField find_llinatge2;
    private javax.swing.JTextField find_nom;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l_e_conjuge1;
    private javax.swing.JLabel l_e_conjuge2;
    private javax.swing.JLabel l_generacio;
    private javax.swing.JLabel l_mare;
    private javax.swing.JLabel l_mmare;
    private javax.swing.JLabel l_mmmare;
    private javax.swing.JLabel l_mmpare;
    private javax.swing.JLabel l_mpare;
    private javax.swing.JLabel l_mpmare;
    private javax.swing.JLabel l_mppare;
    private javax.swing.JLabel l_pare;
    private javax.swing.JLabel l_pmare;
    private javax.swing.JLabel l_pmmare;
    private javax.swing.JLabel l_pmpare;
    private javax.swing.JLabel l_ppare;
    private javax.swing.JLabel l_ppmare;
    private javax.swing.JLabel l_pppare;
    private javax.swing.JList ll_ufills;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mu_csv;
    private javax.swing.JMenuItem mu_taula;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPanel panelVisor;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JTextField t_1any;
    private javax.swing.JTextArea t_1comentaris;
    private javax.swing.JTextField t_1dany;
    private javax.swing.JTextArea t_2comentaris;
    private javax.swing.JTextField t_2dany;
    private javax.swing.JTextField t_2llinatge1;
    private javax.swing.JTextField t_2llinatge2;
    private javax.swing.JTextField t_2nany;
    private javax.swing.JTextField t_2nom;
    private javax.swing.JTextField t_e_1llinatge1;
    private javax.swing.JTextField t_e_1llinatge2;
    private javax.swing.JTextField t_e_1nom;
    private javax.swing.JTextField t_fitxa;
    private javax.swing.JTextArea t_ucomentaris;
    private javax.swing.JPanel topleft;
    private javax.swing.JPanel topright;
    private javax.swing.JPanel treepanel;
    private javax.swing.JLabel v_conj1;
    private javax.swing.JLabel v_conj2;
    private javax.swing.JLabel v_fitxa;
    private javax.swing.JLabel v_h_defuncio;
    private javax.swing.JLabel v_h_mare;
    private javax.swing.JLabel v_h_mmare;
    private javax.swing.JLabel v_h_mpare;
    private javax.swing.JLabel v_h_naixement;
    private javax.swing.JLabel v_h_nom;
    private javax.swing.JLabel v_h_pare;
    private javax.swing.JLabel v_h_pares;
    private javax.swing.JLabel v_h_pares1;
    private javax.swing.JLabel v_h_pares2;
    private javax.swing.JLabel v_h_pares4;
    private javax.swing.JLabel v_h_pares5;
    private javax.swing.JLabel v_h_pmare;
    private javax.swing.JLabel v_h_ppare;
    private javax.swing.JLabel v_m_defuncio;
    private javax.swing.JLabel v_m_mare;
    private javax.swing.JLabel v_m_mmare;
    private javax.swing.JLabel v_m_mpare;
    private javax.swing.JLabel v_m_naixement;
    private javax.swing.JLabel v_m_nom;
    private javax.swing.JLabel v_m_pare;
    private javax.swing.JLabel v_m_pares;
    private javax.swing.JLabel v_m_pmare;
    private javax.swing.JLabel v_m_ppare;
    private javax.swing.JButton vb_h_mpares;
    private javax.swing.JButton vb_h_pares;
    private javax.swing.JButton vb_h_ppares;
    private javax.swing.JButton vb_m_mpares;
    private javax.swing.JButton vb_m_pares;
    private javax.swing.JButton vb_m_ppares;
    // End of variables declaration//GEN-END:variables
    private popupPersonaCerca ppc;
    private popupPersonaFill ppf;
        
    private void novaFitxa() {
        String sf = JOptionPane.showInputDialog(null, "Número de fitxa a carregar",
                "Carregar fitxa", JOptionPane.OK_CANCEL_OPTION);
        if (!(sf==null || sf.isEmpty())){
            try{
                int fitxa = Integer.parseInt(sf);
                if(!db.unio.existFitxa(fitxa)){
                    throw new DBException();
                }else{
                    f.fillFitxa(fitxa);
                }
            }catch (NumberFormatException | DBException e){
                new GException("La fitxa introduida no és correcte.", "Fitxa incorrete").show();
            }
        }
    }

    private void tancar() {
        System.out.println("Fins aviat!");
        System.exit(0);
    }
    
}
