/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geneal.nbforms;

import Exceptions.DBException;
import geneal.sourceforms.formData;
import geneal.sourceforms.formLloc;
import geneal.sourceforms.formPersona;
import static geneal.config.*;
import static geneal.sourceforms.formutils.getModelSexe;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jordi
 */
public class ModifyPerson extends javax.swing.JFrame {

    private final formLloc fnaixement, fdef;
    private final formData dnaixement, ddef;
    private final formPersona person;
    private final javax.swing.ComboBoxModel cbsexe = getModelSexe();
    
    /**
     * Creates new form ModifyPerson
     * @param p
     */
    public ModifyPerson(db.persona p) {
        initComponents();
        
        fnaixement = new formLloc(this.c_municipi, this.c_parroquia, this.c_llogaret);
        fdef = new formLloc(this.c_dmunicipi, this.c_dparroquia, this.c_dllogaret);
        dnaixement = new formData(this.c_dia, this.c_mes, this.t_any);
        ddef = new formData(this.c_ddia, this.c_dmes, this.t_dany);
        
        javax.swing.JTextField[] nom = {this.t_nom, this.t_llinatge1,  this.t_llinatge2};
        
        person = new formPersona(fnaixement, fdef, dnaixement, ddef, nom, this.t_comentaris,
                this.c_sexe, this.l_);
        
        try {
            person.fill(p);
        } catch (DBException ex) {
            ex.show();
            Logger.getLogger(ModifyPerson.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public formPersona getFormPerson(){
        return this.person;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        l_ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_nom = new javax.swing.JTextField();
        t_llinatge1 = new javax.swing.JTextField();
        t_llinatge2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_municipi = new javax.swing.JComboBox();
        c_parroquia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        c_llogaret = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        c_dia = new javax.swing.JComboBox();
        c_mes = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_any = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        c_dmunicipi = new javax.swing.JComboBox();
        c_dparroquia = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c_dllogaret = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        c_ddia = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        c_dmes = new javax.swing.JComboBox();
        t_dany = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        c_sexe = new javax.swing.JComboBox();
        b_guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_comentaris = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geneal - Modificar persona");

        mainPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPane.setPreferredSize(new java.awt.Dimension(500, 320));
        mainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_.setFont(boldFont);
        l_.setText("Conjuge1");
        mainPane.add(l_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(normalFont);
        jLabel2.setText("Nom");
        mainPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        t_nom.setFont(normalFont);
        mainPane.add(t_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, -1));

        t_llinatge1.setFont(normalFont);
        mainPane.add(t_llinatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        t_llinatge2.setFont(normalFont);
        mainPane.add(t_llinatge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 150, -1));

        jLabel4.setFont(normalFont);
        jLabel4.setText("Primer llinatge");
        mainPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel5.setFont(normalFont);
        jLabel5.setText("Segon llinatge");
        mainPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel6.setFont(normalFont);
        jLabel6.setText("Naixement:");
        mainPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(smallFont);
        jLabel7.setText("Municipi");
        mainPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        c_municipi.setFont(normalFont);
        c_municipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_municipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_municipiActionPerformed(evt);
            }
        });
        c_municipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_municipiFocusLost(evt);
            }
        });
        mainPane.add(c_municipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, -1));

        c_parroquia.setFont(normalFont);
        c_parroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_parroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_parroquiaActionPerformed(evt);
            }
        });
        mainPane.add(c_parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, -1));

        jLabel8.setFont(smallFont);
        jLabel8.setText("Parroquia");
        mainPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 94, -1));

        c_llogaret.setFont(normalFont);
        c_llogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_llogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_llogaretActionPerformed(evt);
            }
        });
        mainPane.add(c_llogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, -1));

        jLabel9.setFont(smallFont);
        jLabel9.setText("Llogaret");
        mainPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 94, -1));

        c_dia.setFont(normalFont);
        mainPane.add(c_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, -1));

        c_mes.setFont(normalFont);
        c_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_mesActionPerformed(evt);
            }
        });
        mainPane.add(c_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 60, -1));

        jLabel10.setFont(smallFont);
        jLabel10.setText("Dia");
        mainPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 94, -1));

        jLabel11.setFont(smallFont);
        jLabel11.setText("Mes");
        mainPane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 94, -1));

        jLabel12.setFont(smallFont);
        jLabel12.setText("Any");
        mainPane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 70, -1));

        t_any.setFont(normalFont);
        mainPane.add(t_any, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 50, -1));

        jLabel13.setFont(normalFont);
        jLabel13.setText("Defunció");
        mainPane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel14.setFont(smallFont);
        jLabel14.setText("Municipi");
        mainPane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        c_dmunicipi.setFont(normalFont);
        c_dmunicipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_dmunicipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dmunicipiActionPerformed(evt);
            }
        });
        c_dmunicipi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_dmunicipiFocusLost(evt);
            }
        });
        mainPane.add(c_dmunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        c_dparroquia.setFont(normalFont);
        c_dparroquia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_dparroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dparroquiaActionPerformed(evt);
            }
        });
        mainPane.add(c_dparroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 90, -1));

        jLabel15.setFont(smallFont);
        jLabel15.setText("Parroquia");
        mainPane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 94, -1));

        jLabel16.setFont(smallFont);
        jLabel16.setText("Llogaret");
        mainPane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 94, -1));

        c_dllogaret.setFont(normalFont);
        c_dllogaret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        c_dllogaret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dllogaretActionPerformed(evt);
            }
        });
        mainPane.add(c_dllogaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, -1));

        jLabel17.setFont(smallFont);
        jLabel17.setText("Dia");
        mainPane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 94, -1));

        c_ddia.setFont(normalFont);
        mainPane.add(c_ddia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, -1));

        jLabel18.setFont(smallFont);
        jLabel18.setText("Mes");
        mainPane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 94, -1));

        c_dmes.setFont(normalFont);
        c_dmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dmesActionPerformed(evt);
            }
        });
        mainPane.add(c_dmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 60, -1));

        t_dany.setFont(normalFont);
        t_dany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_danyActionPerformed(evt);
            }
        });
        mainPane.add(t_dany, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 50, -1));

        jLabel19.setFont(smallFont);
        jLabel19.setText("Any");
        mainPane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 50, -1));

        jLabel21.setFont(normalFont);
        jLabel21.setText("Sexe");
        mainPane.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        c_sexe.setFont(normalFont);
        c_sexe.setModel(cbsexe);
        c_sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_sexeActionPerformed(evt);
            }
        });
        mainPane.add(c_sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 20));

        b_guardar.setFont(normalFont);
        b_guardar.setText("Guardar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });
        mainPane.add(b_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 20));

        t_comentaris.setColumns(20);
        t_comentaris.setFont(normalFont);
        t_comentaris.setRows(5);
        jScrollPane1.setViewportView(t_comentaris);

        mainPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 340, 40));

        jLabel22.setFont(normalFont);
        jLabel22.setText("Comentaris");
        mainPane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        mainPane.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -120, -1, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_municipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_municipiActionPerformed
        this.fnaixement.selectedMunicipi();
    }//GEN-LAST:event_c_municipiActionPerformed

    private void c_municipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_municipiFocusLost
        this.fnaixement.selectedMunicipi();
    }//GEN-LAST:event_c_municipiFocusLost

    private void c_parroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_parroquiaActionPerformed
        this.fnaixement.selectedParroquia();
    }//GEN-LAST:event_c_parroquiaActionPerformed

    private void c_llogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_llogaretActionPerformed
        this.fnaixement.selectedLlogaret();
    }//GEN-LAST:event_c_llogaretActionPerformed

    private void c_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_mesActionPerformed

    private void c_dmunicipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dmunicipiActionPerformed
        this.fdef.selectedMunicipi();
    }//GEN-LAST:event_c_dmunicipiActionPerformed

    private void c_dmunicipiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_dmunicipiFocusLost
        this.fdef.selectedMunicipi();
    }//GEN-LAST:event_c_dmunicipiFocusLost

    private void c_dparroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dparroquiaActionPerformed
        this.fdef.selectedParroquia();
    }//GEN-LAST:event_c_dparroquiaActionPerformed

    private void c_dllogaretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dllogaretActionPerformed
        this.fdef.selectedLlogaret();
    }//GEN-LAST:event_c_dllogaretActionPerformed

    private void c_dmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_dmesActionPerformed

    private void t_danyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_danyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_danyActionPerformed

    private void c_sexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_sexeActionPerformed
        this.l_.setText(String.valueOf(this.c_sexe.getSelectedItem()));
    }//GEN-LAST:event_c_sexeActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        end();
    }//GEN-LAST:event_b_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JComboBox c_ddia;
    private javax.swing.JComboBox c_dia;
    private javax.swing.JComboBox c_dllogaret;
    private javax.swing.JComboBox c_dmes;
    private javax.swing.JComboBox c_dmunicipi;
    private javax.swing.JComboBox c_dparroquia;
    private javax.swing.JComboBox c_llogaret;
    private javax.swing.JComboBox c_mes;
    private javax.swing.JComboBox c_municipi;
    private javax.swing.JComboBox c_parroquia;
    private javax.swing.JComboBox c_sexe;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel l_;
    private javax.swing.JPanel mainPane;
    private javax.swing.JTextField t_any;
    private javax.swing.JTextArea t_comentaris;
    private javax.swing.JTextField t_dany;
    private javax.swing.JTextField t_llinatge1;
    private javax.swing.JTextField t_llinatge2;
    private javax.swing.JTextField t_nom;
    // End of variables declaration//GEN-END:variables

    public void end() {
        person.add();
        this.dispose();
    }
}
